 name: Actions Workflows

 #on: [push, pull_request]
 #on:
 # push:
   # branches:
   #   - main #for main branch
      #- 'feature/*' #matches features/featA,feature/featB
      #doesn't match feature/feat/A
    #  - 'feature/**'
    #  - '!feature/featc' #ignor the branch
   # tags:
   #  - v1.*
   # paths:
    # - '**.js'
     
#branches-ignore:
      #- null #we can't use branches and branches ignor same time
 #its is used to trigger manually and using api also u can trigger
    #repository_dispatch:
    #push:
    #pull_request:
    # types: [closed, assigned, opened, reopened]
    #schedule:
    #  - cron: "0/5 * * * *"
     # - cron: "0/8 * * * *"

#use simple action to print Hello +InputString javascript action
 jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List of the files
        run: |
           ls
           pwd
           echo $GITHUB_SHA
           echo $GITHUB_REPOSITORY
           echo $GITHUB_WORKSPACE
           echo "${{ github.token }}"
           #git clone git@github:$GITHUB_REPOSITORY
           #git checkout $GITHUB_SHA
           
      #clone your repository into your virtual machine for we used chekout action
      #it is offficial action means created by github
      #
      - name: Checkout
        uses: actions/checkout@v1
      #after checkout  
      - name: List of the files
        run: |
           ls -a
           pwd  
        
      - name: Simple js acion
      #using below action it will print Hello and some input string
        id: greet
        uses: actions/hello-world-javascript-action@v1
      #To give input string we used with and who-to-greet  
        with: 
          who-to-greet: Nisha
      #If u want to print the log for that u have use id 
      - name: Log Greeting Time
        run: echo "${{steps.greet.outputs.time}}"
          
